name: Verification build

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "test/**"

env:
  Hangfire_Cockroach_DatabaseName: defaultdb
  Hangfire_Cockroach_SchemaName: hangfire
  Hangfire_Cockroach_ConnectionStringTemplate: "Host=localhost; Port=26257; Database=defaultdb; SSL Mode=disable;Include Error Detail=true"

permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      cockroachdb:
        image: cockroachdb/cockroach
        env:
          TZ: UTC
          PGTZ: UTC
        options: >-
          start-single-node
          --insecure
          --listen-addr=localhost:26257
          --http-addr=localhost:8080
        ports:
          - 26257:26257
          - 8080:8080
        volumes:
          - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx"
      - name: Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: "**/TestResults.trx"
