name: Verification build

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]
    paths:
      - "src/**"
      - "test/**"

 
permissions: write-all

jobs:
  build-and-test:
    runs-on: ubuntu-latest
 
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Start a single CockroachDB instance
        run: |
            docker pull cockroachdb/cockroach
            docker run -d --name roach --hostname roach -p 26257:26257 -p 8080:8080 cockroachdb/cockroach start-single-node --insecure
            sudo apt update && sudo apt install wait-for-it -y
            wait-for-it -h localhost -p 26257

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=TestResults.trx"
      - name: Test Report
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: "**/TestResults.trx"
